 gen_pops <- generate_pop(coef_outcome_p_score = get_default_cov("outcome_p_score"),
                          coef_outcome = get_default_cov("outcome"),
                          coef_p_score = get_default_cov("p_score"),
                          hte = list(mean = 10, var = 1),
                          Ni_size  = 1000,
                          m = 50,
                          no_sim = 10,
                          regression_type = "continuous", 
                          additional_params = list(frac_out = 0.05,
                                                   re = list(var_re = 3,
                                                   frac_out_re = 0.25,
                                                   var_re_out = 10, 
                                                   mean_re_out = 15),
                                                   var_re_treat  = 0.25,
                                                   params_cont = list(var_e = 6,
                                                   var_e_out = 150,
                                                   mean_e_out = 20), 
                                                   disturbance = 5), 
                                                   start_seed = 1)
