Province <- numeric(41)
Province[which(tau_EB[[1]]$group == 84)] <- "Agrigento"
Province[which(tau_EB[[1]]$group == 42)] <- "Ancona"
Province[which(tau_EB[[1]]$group == 51)] <- "Arezzo"
Province[which(tau_EB[[1]]$group == 44)] <- "Ascoli-Piceno"
Province[which(tau_EB[[1]]$group == 64)] <- "Avellino"
Province[which(tau_EB[[1]]$group == 62)] <- "Benevento"
Province[which(tau_EB[[1]]$group == 16)] <- "Bergamo"
Province[which(tau_EB[[1]]$group == 17)] <- "Brescia"

Province[which(tau_EB[[1]]$group == 85)] <- "Caltanissetta"
Province[which(tau_EB[[1]]$group == 61)] <- "Caserta"
Province[which(tau_EB[[1]]$group == 87)] <- "Catania"
Province[which(tau_EB[[1]]$group == 13)] <- "Como"
Province[which(tau_EB[[1]]$group == 19)] <- "Cremona"
Province[which(tau_EB[[1]]$group == 86)] <- "Enna"
Province[which(tau_EB[[1]]$group == 48)] <- "Firenze"
Province[which(tau_EB[[1]]$group == 53)] <- "Grosseto"

Province[which(tau_EB[[1]]$group == 97)] <- "Lecco"
Province[which(tau_EB[[1]]$group == 49)] <- "Livorno"
Province[which(tau_EB[[1]]$group == 98)] <- "Lodi"
Province[which(tau_EB[[1]]$group == 46)] <- "Lucca"
Province[which(tau_EB[[1]]$group == 43)] <- "Macerata"
Province[which(tau_EB[[1]]$group == 20)] <- "Mantova"
Province[which(tau_EB[[1]]$group == 45)] <- "Massa-Carrara"
Province[which(tau_EB[[1]]$group == 83)] <- "Messina"

Province[which(tau_EB[[1]]$group == 15)] <- "Milano"
Province[which(tau_EB[[1]]$group == 63)] <- "Napoli"
Province[which(tau_EB[[1]]$group == 82)] <- "Palermo"
Province[which(tau_EB[[1]]$group == 18)] <- "Pavia"
Province[which(tau_EB[[1]]$group == 54)] <- "Perugia"
Province[which(tau_EB[[1]]$group == 41)] <- "Pesaro-Urbino"
Province[which(tau_EB[[1]]$group == 50)] <- "Pisa"
Province[which(tau_EB[[1]]$group == 47)] <- "Pistoia"

Province[which(tau_EB[[1]]$group == 100)] <- "Prato"
Province[which(tau_EB[[1]]$group == 88)] <- "Ragusa"
Province[which(tau_EB[[1]]$group == 65)] <- "Salerno"
Province[which(tau_EB[[1]]$group == 52)] <- "Siena"
Province[which(tau_EB[[1]]$group == 89)] <- "Siracusa"
Province[which(tau_EB[[1]]$group == 14)] <- "Sondrio"
Province[which(tau_EB[[1]]$group == 55)] <- "Terni"
Province[which(tau_EB[[1]]$group == 81)] <- "Trapani"

Province[which(tau_EB[[1]]$group == 12)] <- "Varese"
